#!/usr/bin/env bash
# Usage: assemble-reports.sh <input-dir> <output-dir>
# Lays junit.xml, coverage.xml and htmlcov/ out as the reports/ tree that
# apis.ryankes.eu serves (tests/, coverage/, index.html). Fails if an input
# is missing, so a run that produced no reports publishes nothing.
set -euo pipefail
in="${1:?input dir}"
out="${2:?output dir}"

for f in junit.xml coverage.xml htmlcov/index.html; do
  [ -f "$in/$f" ] || { echo "missing $in/$f" >&2; exit 1; }
done

mkdir -p "$out/tests" "$out/coverage"
cp "$in/junit.xml" "$out/tests/junit.xml"
cp -r "$in/htmlcov/." "$out/coverage/"
cp "$in/coverage.xml" "$out/coverage/coverage.xml"
rm -f "$out/coverage/.gitignore"

cat > "$out/index.html" <<'HTML'
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>pipeline-analytics-sdk-python reports</title>
</head>
<body>
<main>
<h1>pipeline-analytics-sdk-python reports</h1>
<p>Generated by the last green run on the default branch.</p>
<ul>
<li><a href="tests/junit.xml">Test results (JUnit XML)</a></li>
<li><a href="coverage/">Coverage report</a></li>
<li><a href="coverage/coverage.xml">Coverage (Cobertura XML)</a></li>
</ul>
</main>
</body>
</html>
HTML
